### ISSUE TITLE
Cron Manager doesn't work with "exit"

### ISSUE THREAD

**Issue by Heavlock** [Jako/CronManager#44]
The Cron manager does not work with " exit ()". If I use exit() in a code snippet, the time is not transferred to the next iteration. As a result, one snippet starts executing indefinitely and blocks the work of the others

**Comment by Jako** [comment]
With an exit the end of the snippet the result can't be detected by CronManager, since CronManager is stopped with the exit too. So it can't write any success or failure message to the database.

Since 1.2.2 the snippet will be executed with the `CronManager = 1` property. This can be used to detect, if the snippet is called inside of CronManager.
