### ISSUE TITLE
Logs grid: day collapsible title renders false instead of the actual date

### ISSUE THREAD

**Issue by travisbotello** [Jako/CronManager#53]
![Screenshot 2022-09-06 at 13 53 02](https://user-images.githubusercontent.com/1157380/188655271-774b17fc-7c27-4b18-9fb5-0296dea0b610.png)

MODX 2.8.4
PHP 7.4
CronManager 1.2.7

**Comment by Jako** [comment]
This should be fixed with 1.2.8. Please use the changes in https://github.com/Jako/CronManager/commit/cc1b4c896ba3fe303a79c95d016b64c85731fdb6 in the files cronmanager.min.js and the two getlist.class.php. Or use the 1.2.8-rc1 package to installl the latest version https://github.com/Jako/CronManager/blob/cc1b4c896ba3fe303a79c95d016b64c85731fdb6/_packages/cronmanager-1.2.8-rc1.transport.zip. Can you tell me, wether this is fixed with that version?

**Comment by Jako** [comment]
This is fixed with 1.3.0.
