### ISSUE TITLE
CronManager grid renders wrong datetime offset for nextrun/lastrun in manager

### ISSUE THREAD

**Issue by travisbotello** [Jako/CronManager#54]
Server and PHP timezone are set to Europe/Berlin. MODX error log messages show correct datetime in database + MODX manager:

![Screenshot 2022-09-06 at 16 09 19](https://user-images.githubusercontent.com/1157380/188657083-4124390d-c4c6-4210-be68-f1cf1c1cc437.png)
![Screenshot 2022-09-06 at 16 05 08](https://user-images.githubusercontent.com/1157380/188656648-076f507f-308b-43bf-bc89-178c63627977.png)

Nextrun and lastrun columns are displayed with a +2 hours offset from their database values.

![Screenshot 2022-09-06 at 16 06 06](https://user-images.githubusercontent.com/1157380/188656858-5ae0dc8e-33b5-4ad7-a390-20a13aea8a42.png)
![Screenshot 2022-09-06 at 16 05 54](https://user-images.githubusercontent.com/1157380/188656864-7c678d0d-8a02-45f2-a5e9-e80eb7d65df6.png)

MODX 2.8.4
PHP 7.4
CronManager 1.2.7

**Comment by Jako** [comment]
This should be fixed with 1.2.8. Please use the changes in https://github.com/Jako/CronManager/commit/cc1b4c896ba3fe303a79c95d016b64c85731fdb6 in the files `cronmanager.min.js` and the two getlist.class.php. Or use the 1.2.8-rc1 package to installl the latest version https://github.com/Jako/CronManager/blob/cc1b4c896ba3fe303a79c95d016b64c85731fdb6/_packages/cronmanager-1.2.8-rc1.transport.zip. Can you tell me, wether this is fixed with that version?

**Comment by Jako** [comment]
This is fixed with 1.3.0.
